---
- name: Get the details of the Service and check if k8s connection is working
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: meas-api
    namespace: meas-api
  register: meas_service

- name: Print the specs of the Service.
  debug:
    var: meas_service.resources[0].spec
